# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.6/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.6/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mohi/workspace/c++/odyssey

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mohi/workspace/c++/odyssey

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.6/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.9.6/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mohi/workspace/c++/odyssey/CMakeFiles /Users/mohi/workspace/c++/odyssey/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mohi/workspace/c++/odyssey/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named odyssey

# Build rule for target.
odyssey: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 odyssey
.PHONY : odyssey

# fast build rule for target.
odyssey/fast:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/build
.PHONY : odyssey/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/main.cpp.s
.PHONY : main.cpp.s

types/Scheduler.o: types/Scheduler.cpp.o

.PHONY : types/Scheduler.o

# target to build an object file
types/Scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/types/Scheduler.cpp.o
.PHONY : types/Scheduler.cpp.o

types/Scheduler.i: types/Scheduler.cpp.i

.PHONY : types/Scheduler.i

# target to preprocess a source file
types/Scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/types/Scheduler.cpp.i
.PHONY : types/Scheduler.cpp.i

types/Scheduler.s: types/Scheduler.cpp.s

.PHONY : types/Scheduler.s

# target to generate assembly for a file
types/Scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/types/Scheduler.cpp.s
.PHONY : types/Scheduler.cpp.s

types/task.o: types/task.cpp.o

.PHONY : types/task.o

# target to build an object file
types/task.cpp.o:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/types/task.cpp.o
.PHONY : types/task.cpp.o

types/task.i: types/task.cpp.i

.PHONY : types/task.i

# target to preprocess a source file
types/task.cpp.i:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/types/task.cpp.i
.PHONY : types/task.cpp.i

types/task.s: types/task.cpp.s

.PHONY : types/task.s

# target to generate assembly for a file
types/task.cpp.s:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/types/task.cpp.s
.PHONY : types/task.cpp.s

types/worker.o: types/worker.cpp.o

.PHONY : types/worker.o

# target to build an object file
types/worker.cpp.o:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/types/worker.cpp.o
.PHONY : types/worker.cpp.o

types/worker.i: types/worker.cpp.i

.PHONY : types/worker.i

# target to preprocess a source file
types/worker.cpp.i:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/types/worker.cpp.i
.PHONY : types/worker.cpp.i

types/worker.s: types/worker.cpp.s

.PHONY : types/worker.s

# target to generate assembly for a file
types/worker.cpp.s:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/types/worker.cpp.s
.PHONY : types/worker.cpp.s

utils/tgparser.o: utils/tgparser.cpp.o

.PHONY : utils/tgparser.o

# target to build an object file
utils/tgparser.cpp.o:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/utils/tgparser.cpp.o
.PHONY : utils/tgparser.cpp.o

utils/tgparser.i: utils/tgparser.cpp.i

.PHONY : utils/tgparser.i

# target to preprocess a source file
utils/tgparser.cpp.i:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/utils/tgparser.cpp.i
.PHONY : utils/tgparser.cpp.i

utils/tgparser.s: utils/tgparser.cpp.s

.PHONY : utils/tgparser.s

# target to generate assembly for a file
utils/tgparser.cpp.s:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/utils/tgparser.cpp.s
.PHONY : utils/tgparser.cpp.s

utils/utils.o: utils/utils.cpp.o

.PHONY : utils/utils.o

# target to build an object file
utils/utils.cpp.o:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/utils/utils.cpp.o
.PHONY : utils/utils.cpp.o

utils/utils.i: utils/utils.cpp.i

.PHONY : utils/utils.i

# target to preprocess a source file
utils/utils.cpp.i:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/utils/utils.cpp.i
.PHONY : utils/utils.cpp.i

utils/utils.s: utils/utils.cpp.s

.PHONY : utils/utils.s

# target to generate assembly for a file
utils/utils.cpp.s:
	$(MAKE) -f CMakeFiles/odyssey.dir/build.make CMakeFiles/odyssey.dir/utils/utils.cpp.s
.PHONY : utils/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... odyssey"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... types/Scheduler.o"
	@echo "... types/Scheduler.i"
	@echo "... types/Scheduler.s"
	@echo "... types/task.o"
	@echo "... types/task.i"
	@echo "... types/task.s"
	@echo "... types/worker.o"
	@echo "... types/worker.i"
	@echo "... types/worker.s"
	@echo "... utils/tgparser.o"
	@echo "... utils/tgparser.i"
	@echo "... utils/tgparser.s"
	@echo "... utils/utils.o"
	@echo "... utils/utils.i"
	@echo "... utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

